### ISSUE TITLE
Add bindsym in Xresource

### ISSUE THREAD

**Issue by cheginit** [regolith-linux/regolith-i3-gaps-config#10]
I tried to add bindsym for programs in the Xresource file but it's not working. Here is what I did:
in the `~/.config/regolith/i3/config` file:
```bash
set_from_resource $i3-wm.bindsym.1 i3-wm.bindsym.1 :
set_from_resource $i3-wm.bindsym.program.1 i3-wm.bindsym.program.1 :
bindsym $i3-wm.bindsym.1 exec --no-startup-id "$i3-wm.bindsym.program.1"
```
in the `~/.config/regolith/Xresource` file
```
i3-wm.mod: Mod4
i3-wm.bindsym.1: $i3-wm.mod+c
i3-wm.bindsym.program.1: rofi -show calc -modi calc -no-show-match -no-sort
```

**Comment by cheginit** [comment]
I solved it as follows:
in the `~/.config/regolith/i3/config` file:
```bash
set_from_resource $i3-wm.bindsym.1 i3-wm.bindsym.1 :
set_from_resource $i3-wm.bindsym.program.1 i3-wm.bindsym.program.1 :
bindsym $mod+$i3-wm.bindsym.1 exec --no-startup-id "$i3-wm.bindsym.program.1"
```
in the `~/.config/regolith/Xresource` file:
```bash
i3-wm.bindsym.1: c
i3-wm.bindsym.program.1: rofi -show calc -modi calc -no-show-match -no-sort
```
It seems that  `$mod` part of the key should be included in the i3 config file rather than the xresource.

**Comment by cheginit** [comment]
@kgilmer If you have a better solution let me know. If not I will close the issue.

**Comment by kgilmer** [comment]
I'd like to add a few of these to the default for 1.4.  Did you close this issue @cheginit because there was a problem?  (I was focusing elsewhere for the past few days so didn't see this until now.)

**Comment by cheginit** [comment]
@kgilmer No, it works without any issue. I closed it since the problem is resolved and I thought you didn't have any suggestions.

Adding it wouble be cool. The only downside to this solution is that by default it assumes that the first key is always `Super` so the user should be mindful of that. Also, keybindings cannot have any of the mods i.e, no `$` can be used in the `Xresource` file. Other than that it works pretty well.

**Comment by kgilmer** [comment]
Got it, and good to know about the limitations.  Thanks @cheginit !

**Comment by kgilmer** [comment]
I looked into adding this into the Regolith config, but lacking the ability to predicate from Xresource state, I don't see a way of not consuming a keybinding that's a no-op unless the user defines it.  So, if I wanted to create 3 user keybindings, I would have to already define them and have them be taken by i3.  Am I missing anything?

**Comment by cheginit** [comment]
If I understand you correctly, it follows the same pattern as the exec that you have added 5 of them. The keybinding part that needs to be added in i3 is `$mod+$i3-wm.bindsym.1` which gives the user the ability to use keys like `c`, `Shift+c`,or `Ctrl+c`.

**Comment by kgilmer** [comment]
Right, I guess the difference is that just doing exec is more of a 'fire and forget' style operation, where as keybinding declarations have global static scope.  So, I cannot see a way of allowing user to provide keybindings without pre-reserving them.

**Comment by cheginit** [comment]
Well, not necessarily. Upon reloading, if the keybinding has already been assigned i3 throws an error and shows the conflict so the user can easily fix the issue.

**Comment by kgilmer** [comment]
Conflict?  I'm talking more about the base case of just the default configuration.  I cannot think of a way of adding an **optional** keybinding statement which does nothing until/if the user specifies an Xresource kvp for a given keybinding.

**Comment by cheginit** [comment]
I thought by adding `:` the default is taken care of it, isn't it?
