### ISSUE TITLE
 Assigning workspace to monitor creates duplicated workspaces

### ISSUE THREAD

**Issue by donce** [regolith-linux/regolith-i3-gaps-config#11]
I'm having the same issue which was discussed in https://github.com/regolith-linux/regolith-i3/issues/12

This produces config errors:
```
workspace $ws1 output DP1
```

Another solution is to use the index:
```
workspace 1 output DP1
```
This works, but instead of creating "1 [ ]" workspace with a color square, it creates a workspace without a color square. This is annoying, because you can have both "1" and "1 [ ]" workspaces at the same time, which breaks workspace navigation shortcuts making this feature unusable.
![second](https://user-images.githubusercontent.com/1409983/79785371-a99a6b00-833b-11ea-8749-12f7e1e69c43.png)
![first](https://user-images.githubusercontent.com/1409983/79785366-a901d480-833b-11ea-9ff5-1d77075c6dcb.png)

I'm using `4.17.1`:
```
i3 --moreversion
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 2649)abort…)
Loaded i3 config: /home/donatas/.config/regolith/i3/config (Last modified: Mon 20 Apr 2020 19:03:49 BST, 959 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

**Comment by donce** [comment]
After upgrading ubuntu to 20.04, this is no longer the case.

**Comment by donce** [comment]
Actually, it still happens - it seems that the problem happens only when the workspace has to be created for a new window. It creates a workspace without the special character. If workspace was already created when new window is assigned to the workspace - when the correct workspace is re-used.

**Comment by moritzheiber** [comment]
Would you mind attaching your configuration?

**Comment by leachim742** [comment]
I had the same Issue. I solved the Problem like this :  workspace "$ws1" output DP1 .

My Binary i3 version:  4.17.1

**Comment by ferdinandyb** [comment]
Yes, I can confirm the solution is to use `"$ws1"` with the quotes. @kgilmer Could this warrant a how-to on the webpage? I think this is the only situation that requires to use the quotes in the config, at least that I came across, so is not entirely trivial.

**Comment by kgilmer** [comment]
Created new issue to add documentation.  Closing issue as original issue appears addressed.
