### ISSUE TITLE
Might be this a old configuration?

### ISSUE THREAD

**Issue by nachovizzo** [regolith-linux/regolith-i3-gaps-config#12]
https://github.com/regolith-linux/regolith-i3-gaps-config/blob/367902a92a4607026d28ea87678b9b1b08fc6204/config#L80

In the latest release, regolith switched to `lascaille` theme who defines the rofi theme to be
```sh
styles/lascaille/root
15:#include "/etc/regolith/styles/rofi"

styles/lascaille/theme
4:#define rofi_theme          /etc/regolith/styles/lascaille/rofi.rasi
```

I don't even have the cahuela theme installed on my system anymore

BTW: I do like the update, besides the fact  I have to spend 1 hour tweaking the configurations :)

I'd love to contribute somehow so next time is easier to do the transition

**Comment by kgilmer** [comment]
Nice find!  It shouldn't have an impact as it's only specifying a fallback in case your rofi theme is not set, but it should be by the look you have set.  You can verify w/ `xrescat`.  In any case, I'll fix it.

**Comment by nachovizzo** [comment]
Yup, it makes no problem. I'm glad I found something :)
