### ISSUE TITLE
Is there a way to use the GNOME panel along with i3?

### ISSUE THREAD

**Issue by adityamwagh** [regolith-linux/regolith-i3-gaps-config#26]
It looks like the gnome panel is baked inside the gnome shell. Any way to get that working in regolith desktop?

**Comment by moritzheiber** [comment]
Hey @ad1tyawagh, sorry for not having tended to this sooner. Unfortunately, I believe you're right and there is no way of using gnome-panel with gnome-flashback/i3. However, I would suggest taking a look at alternatives like xfce4-panel or similar panel gadgets.

**Comment by adityamwagh** [comment]
Oh, that's unfortunate. Other panels don't blend in perfectly with i3. Anyways, thanks.
