### ISSUE TITLE
Current i3 config breaks custom workspace names

### ISSUE THREAD

**Issue by deafmute1** [regolith-linux/regolith-i3-gaps-config#35]
Seems like there is a minor issue with the currently shipped i3-gaps config. If a user overrides the default workspace names to any value containing non-digit characters, it breaks all keybinds which operate on that workspace. 

This is because the config references workspaces like this: `workspace number $ws1`. `$ws1` is set by Xresources (i3-wm.workspace.1.name) and is intended to be user editable so that the user can set an arbitrary name, but this current syntax breaks if the `$ws1` is not a integer. Solution is to use this syntax: `workspace number 1 $ws1`, note that I am now directly using the number to reference the workspace, but i3 also allows the pass through the name as a user-friendly identifier. 

The only change to the UX is that the name of the workspace is now `1 <name>`, not `<name>` altough i3-bar has inbuilt functionality to strip the leading number with `strip_workspace_numbers` so the user can have this shown to them in either format regardless.

**Comment by ferdinandyb** [comment]
You just need to set the name to have the numeric identifier as well, for example:
`i3-wm.workspace.01.name: 1:<span font_desc='JetBrains Mono Medium 13'> new name </span> `

Note the `1:` at the beginning.
