### ISSUE TITLE
Is this config backwards compatible with i3-gaps? 

### ISSUE THREAD

**Issue by juliangaal** [regolith-linux/regolith-i3-gaps-config#5]
As I understand it, this config is intended to work with the regolith fork of i3-gaps. Is the config still compatible with i3-gaps, though?

**Comment by kgilmer** [comment]
Hi @juliangaal , as of version 1.2 released in September, Regolith uses stock i3-gaps.  The configuration is compatible with any install assuming the same components are installed such as Rofi.  There has been no change to command parsing or functionality.
